/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : UNO.c
*  Description  : Main Program
*  Creation Date: 2025-09-29
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include <mathf.h>

#define pai 3.141592f

int flag1ms;
float deg;

void main(void);

void main(void)
{
	R_Config_MTU3_MTU4_Start();
	while(1){
	}
}
