/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : UNO.c
*  Description  : Main Program
*  Creation Date: 2025-09-29
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include <mathf.h>

#define pai 3.141592f

int flag1ms;
float deg;

void main(void);

void main(void)
{
	R_Config_MTU0_Start();
	R_Config_MTU4_Start();
	R_Config_CMT0_Start();
	MTU.TRWER.BIT.RWE = 1;
	while(1){
		if(flag1ms==1){
			flag1ms = 0;
			MTU0.TGRA = (MTU0.TGRB / 2) + (MTU0.TGRB / 2) * sinf(deg * pai / 180.0f ) * 0.95f;//Red
			MTU4.TGRA = (MTU4.TGRB / 2) + (MTU4.TGRB / 2) * sinf((deg+120) * pai / 180.0f ) * 0.95f;//Blue
			MTU4.TGRC = (MTU4.TGRB / 2) + (MTU4.TGRB / 2) * sinf((deg-120) * pai / 180.0f ) * 0.95f;//Green
			deg = deg + 0.2f;
			if(deg >= 360) deg = 0;
		}
	}
}
