/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : 2_ADC_Photo.c
*  Description  : Main Program
*  Creation Date: 2025-10-22
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"

unsigned short temp;
float lux;

void main(void);

void main(void)
{
	R_Config_CMT0_Start();
	while(1){
		if(IR(CMT0, CMI0) == 1){
			IR(CMT0, CMI0) = 0;
			R_Config_S12AD0_Start();
			while(IR(S12AD, S12ADI0 == 0));
			R_Config_S12AD0_Get_ValueResult(ADCHANNEL3, &temp);
			lux =  temp * 5.0f / 4096 * 1000 / 3.0f;
		}
	}
}
